### ISSUE TITLE
Threre are some glitches and fissures in dash fragment after zooming in

### ISSUE THREAD

**Issue by vimcaw** [davidfig/pixi-dashed-line#1]
![image](https://user-images.githubusercontent.com/21964227/132606122-bbe69332-a9aa-491d-8e62-bcbb2ece71e0.png)
![image](https://user-images.githubusercontent.com/21964227/132606159-672e611e-e718-4be3-ad27-4d80e151cd18.png)

**Comment by davidfig** [comment]
Are you using options.useTexture?

**Comment by vimcaw** [comment]
I just open the demo page of README.md (https://davidfig.github.io/pixi-dashed-line/).

**Comment by vimcaw** [comment]
Yeah, I just notice there is a checkbox at the right bottom, it only happens on `options.useTexture` opening, anything works well after closing.

**Comment by davidfig** [comment]
Yup. That's known. See the bottom of the readme for a discussion of the issue.

**Comment by vimcaw** [comment]
Oops, sorry, I didn't notice that.
