### ISSUE TITLE
Support cap and join lineStyle options

### ISSUE THREAD

**Issue by vegeta897** [davidfig/pixi-dashed-line#2]
PIXI.Graphics supports different line cap and join styles and it would be great to have these supported when drawing dashed lines.

I did a quick test by editing my `pixi-dashed-line/index.js` to add `cap: PIXI.LINE_CAP.ROUND` and `join: PIXI.LINE_JOIN.ROUND` in the `DashLine` constructor where `lineStyle` is called. It appears to work perfectly when not using textures. 

![image](https://user-images.githubusercontent.com/1789096/136646540-9f4c039a-7196-4340-bb06-b027a189d762.png)

With textures enabled, the caps do not work:
![image](https://user-images.githubusercontent.com/1789096/136646525-08caeaf8-478f-4df5-b66b-b2a62395c835.png)

I don't know whether this is easily fixed, but I think having cap and join style options exposed in the `DashLineOptions` would be a nice addition even if it did require `useTexture: false`.

**Comment by davidfig** [comment]
Good suggestion. I added `options.cap` and `options.join` to v1.1.0. This will not work when `useTexture === true` since there's no support for join and caps with the textured approach. See the readme for a full discussion. Thanks!
