### ISSUE TITLE
Support alignment lineStyle option

### ISSUE THREAD

**Issue by Christoph-Koehler** [davidfig/pixi-dashed-line#3]
It would be nice if the `DashLineOptions ` would support the `alignment` property of `PIXI.Graphics` similar to the `cap `and `join `options as described in #2. 
I also did a quick test by editing the `pixi-dashed-line/index.js` and it also worked for me (with `useTexture: false`).

**Comment by davidfig** [comment]
Thanks for the suggestion. I added options.alignment in v1.2.0.

**Comment by Christoph-Koehler** [comment]
Nice, thanks for the fast response!
